### ISSUE TITLE
Supervisor dying for unknown reason in Docker Container

### ISSUE THREAD

**Issue by delize** [Forceu/barcodebuddy#201]
I use docker-compose to spin up an instance of Barcodebuddy. Recently (in the past 2 months) I have seen the container constantly stop responding. Only now have I been able to get a chance to properly grab logs. 

# Docker Compose file
```
    barcodebuddy:
        container_name: barcodebuddy
        hostname: barcodebuddy
        volumes:
            - '/mnt/cache/docker/barcodebuddy:/config'
        environment:
            - TZ=Europe/Stockholm
            - BBUDDY_DISABLE_AUTHENTICATION=true
            - BBUDDY_CURL_TIMEOUT_S=30n
            - 'BBUDDY_OVERRIDDEN_USER_CONFIG=GROCY_API_URL=https://grocy.${DOMAIN}/api/;GROCY_API_KEY=${GROCY_API}'
            - BASEURL=/barcodebuddy
        # ports:
        #     - '9080:80'
        image: 'f0rc3/barcodebuddy-docker:latest'
        networks:
            - home
            
```

# Docker Log
```
$ docker logs -f barcodebuddy
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

----------------------------------------------------------------------------

 ______                            _       ______            _     _
(____  \                          | |     (____  \          | |   | |
 ____)  ) ____  ____ ____ ___   _ | | ____ ____)  )_   _  _ | | _ | |_   _
|  __  ( / _  |/ ___) ___) _ \ / || |/ _  )  __  (| | | |/ || |/ || | | | |
| |__)  | ( | | |  ( (__| |_| ( (_| ( (/ /| |__)  ) |_| ( (_| ( (_| | |_| |
|______/ \_||_|_|   \____)___/ \____|\____)______/ \____|\____|\____|\__  |
                                                                    (____/

                   Thank you for using our Docker image!

                  https://github.com/Forceu/barcodebuddy
               https://github.com/Forceu/barcodebuddy-docker
---------------------------------------------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-migration: executing...
[cont-init.d] 10-migration: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 60-savearguments: executing...
[EnvParser] Parsing environment variables
[EnvParser] ATTACH_BARCODESCANNER not set, disabling input grabber
[cont-init.d] 60-savearguments: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[info] Starting socket server on 127.0.0.1:47631
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

I could add the `restart: always` option to the compose file, but, I was hoping that there would be a way to get a better understanding as to why it is crashing to prevent the need for that in the future (and hopefully make the service a bit more stable).
