### ISSUE TITLE
api won't connect 

### ISSUE THREAD

**Issue by idaband** [Forceu/barcodebuddy#44]
api is not found.

localhost/api takes you to grocy api.
localhost/api/ errors out on grocy api

so when entering them into barcode buddy api neither works.

barcodebuddy error while connecting gives the following error
Unable to connect to API: Could not connect to server

note:   running both in docker compose to make sure they both applications are in the same network.

**Comment by Forceu** [comment]
Are you using the official Barcode Buddy docker image? Also, are you sure that Barcode Buddy and Grocy are running in the same _container_?

**Comment by idaband** [comment]
Thank you for the quick reply. 

Yes your official BB docker.

barcode buddy would be technically a separate container.  Yes, same docker compose. , but treated as independent container.  Theoretically those should share the same network stack.


Maybe I missed something with that?  or I mis-understand how it's supposed to run correctly.

```
version: '2.4'

services:

  nginx:
    image: "grocy/nginx:v2.6.2-4"
    build:
      args:
        GROCY_VERSION: v2.6.2
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    ports:
      - '127.0.0.1:80:8080'
      - '127.0.0.1:443:8443'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
    container_name: nginx

  grocy:
    image: "grocy/grocy:v2.6.2-4"
    build:
      args:
        GITHUB_API_TOKEN: "${GITHUB_API_TOKEN}"
        GROCY_VERSION: v2.6.2
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php7
      - app-db:/var/www/data
    env_file:
      - grocy.env
    container_name: grocy

  # barcodebuddy:
  #   image: f0rc3/barcodebuddy-docker:latest-dev
  #   ports:
  #     - '127.0.0.1:81:80'
  #     - '127.0.0.1:444:43'
  #   volumes:
  #     - bbconfig:/config
  #   container_name: barcodebuddy
  #   environment: 
  #     - IGNORE_SSL_CA=true
  #   depends_on: 
  #     - grocy


volumes:
  app-db:
  bbconfig:
```
