### ISSUE TITLE
Barcode Buddy Docker with Traefik cannot talk to Grocy

### ISSUE THREAD

**Issue by BradNut** [Forceu/barcodebuddy#91]
I have setup Grocy and Barcode Buddy with Docker compose using Traefik. Both Grocy and Barcode Buddy are available from my subdomain and I am able to use the Grocy Android App which hits my Grocy subdomain successfully. 

On the BBuddy page I enter my Grocy API URL: https://grocy.DOMAIN.com/api/
I also enter my API key created for BBuddy but when hitting save I see the following error:
"Unable to connect to API: Could not connect to server"

I read the docs for Bbuddy regarding Reverse Proxy and noted that the header "X-Accel-Buffering" needs to be passed. As far as I know Traefik passed headers by default but I am not fully sure if this is the problem as the docs do not reference BBuddy behind Traefik.

My docker compose in Traefik looks this:
bbuddy:
    container_name: barcodebuddy
    image: f0rc3/barcodebuddy-docker
    restart: unless-stopped
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/bbuddy/config:/config
    ports:
      - $BARCODE_BUDDY_HTTP_PORT:80
      - $BARCODE_BUDDY_HTTPS_PORT:443
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.bbuddy-rtr.entrypoints=https"
      - "traefik.http.routers.bbuddy-rtr.rule=HostHeader(`bbuddy.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.bbuddy-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      ## HTTP Services
      - "traefik.http.routers.bbuddy-rtr.service=bbuddy-svc"
      - "traefik.http.services.bbuddy-svc.loadbalancer.server.port=80"

**Comment by Forceu** [comment]
Unfortunately I cannot give any support for Traefik. I tried reading into it, but it seems unnecessary complicated (at least v2), maybe someone else can help who is more used to working with Traefik?

**Comment by edenhaus** [comment]
I use traefik and have both running without problems. Have you still problems?

**Comment by BradNut** [comment]
@edenhaus Yes I had the problems mentioned in the initial comment using Traefik 2

**Comment by edenhaus** [comment]
Can you please add your grocy docker-compose configuration (Please add it in a code section for better reading). Can you also put your buddy docker-compose configuration in a coding section.

As I see from the above config, you use a middleware for basic auth, are you also using a basic auth middleware with grocy?
If yes can you try to disable it for testing and verify if the problem still exists.

**Comment by BradNut** [comment]
I am using basic auth as a middleware for most application on my whole setup but for grocy and barcode buddy I did not set it to use auth, defaulting to their built in auth. I see that what I posted had an auth line but I have also tried with no auth line. 

I am able to hit the exposed subdomain and enter the Grocy API and API Key but I see the error message `Unable to connect to API: Could not connect to server`.

Here is my grocy docker-compose config:
```
grocy:
    container_name: grocy
    image: linuxserver/grocy
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/grocy/config:/config
    networks:
      - t2_proxy
    ports:
      - $GROCY_PORT:80
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.grocy-rtr.entrypoints=https"
      - "traefik.http.routers.grocy-rtr.rule=HostHeader(`grocy.$DOMAINNAME`)"
      ## Middlewares
      ## HTTP Services
      - "traefik.http.routers.grocy-rtr.service=grocy-svc"
      - "traefik.http.services.grocy-svc.loadbalancer.server.port=80"
```

Barcode Buddy config:
```
bbuddy:
container_name: barcodebuddy
image: f0rc3/barcodebuddy-docker
restart: unless-stopped
environment:
- TZ=$TZ
volumes:
- $DOCKERDIR/bbuddy/config:/config
ports:
- $BARCODE_BUDDY_HTTP_PORT:80
- $BARCODE_BUDDY_HTTPS_PORT:443
networks:
- t2_proxy
labels:
- "traefik.enable=true"
## HTTP Routers
- "traefik.http.routers.bbuddy-rtr.entrypoints=https"
- "traefik.http.routers.bbuddy-rtr.rule=HostHeader(bbuddy.$DOMAINNAME)"
## Middlewares
## HTTP Services
- "traefik.http.routers.bbuddy-rtr.service=bbuddy-svc"
- "traefik.http.services.bbuddy-svc.loadbalancer.server.port=80"
```
